### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by aymanosman** [Bogdanp/setup-racket#13]
Thanks for this repo.

I tried to add a cache via `actions/cache`.
It breaks this action because `raco` fails of packages are already installed.

If you are interested in supporting this use case, how do you think one would go about fixing this?

**Comment by Bogdanp** [comment]
Instead of caching the entire `~/.racket` folder, what I do is cache just `~/.racket/download-cache`.  This improves download speeds but doesn't help with compilation. I think for the latter, `raco pkg install` would need to change its behavior or add a flag that changes its behavior. I'm not sure there's a non-hacky way for this package to work around that.

**Comment by aymanosman** [comment]
Nice tip. I'll do that.

I agree that this should be handled at the `raco pkg install` level. This issue is related https://github.com/racket/racket/issues/3232.
