### ISSUE TITLE
unknown switch --no-docs on Racket 7.4

### ISSUE THREAD

**Issue by wilbowma** [Bogdanp/setup-racket#18]
When trying to use the `packages` field to install some packages with Racket 7.4, the script fails since `--no-docs` doesn't seem to exist for 7.4

```
  raco pkg install --auto --batch --no-docs --fail-fast compiler-lib
  raco pkg install: unknown switch: --no-docs
Error: The process 'raco' failed with exit code 1
```

https://github.com/wilbowma/test-setup-racket/runs/1654291672?check_suite_focus=true

**Comment by Bogdanp** [comment]
Thanks for the report! Using that flag was probably a bad idea in the first place because someone using that `field` could want to have documentation installed and, if they don't, they can generally install the `-lib` variants of whatever packages they need, like you're doing there. I went ahead and dropped it and cut a new release, `v0.12.1`.
